name: Build and Publish to Play Store
on:
  push:
    branches:
      - release/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Access SERVER_URL
        env:
          SERVER_URL: $
        run: echo '${{ secrets.SERVER_URL }}' > ./apikey.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE_BASE_64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > service_account.json

      - name: Deploy to Play Store (Internal)
        id: deploy
        uses: r0adkll/upload-google-play@v1.0.16
        with:
          track: internal
          serviceAccountJson: service_account.json
          packageName: com.pocs.blog
          status: completed
          releaseFiles: app/build/outputs/bundle/release/app-release.aab