name: Release Tag
on:
  push:
    branches:
      - main
jobs:
  release_tag:
    if: contains(github.event.head_commit.message, 'Release v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract app version
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_version_name.outputs.version }}
          release_name: v${{ steps.extract_version_name.outputs.version }}
          body: ${{ steps.tag_version.outputs.changelog }}
